<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SeleccionarBarrio</name>
   <tag></tag>
   <elementGuidId>33fda3ce-1d3a-490a-9897-64dc370d96a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NeighborhoodId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select ajax-processed ng-untouched ng-pristine ng-invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NeighborhoodId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NeighborhoodId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>NeighborhoodId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Seleccione
                    AlamedaAlcazares-florestaAlfonso LopezAlta VistaAltamiraAndaluciaAntonio NarinoApoloAranjuezAstorgaAuresB. CristobalBarrio ColombiaBarrio Las PalmasBarrio TristeBelalcazarBelenBelencitoBello HorizonteBlanquizalBolivarianoBosques De San PabloBostonBoyaca Las BrisasBuenos AiresCaicedoCalasanzCampo AlegreCampo AmorCampo Valdes 1Campo Valdes 2CarabinerosCaribeCarlos E. RestrepoCastillaCentroCerro De NutibaraColinas Del SurConquistadoresCorazon De JesusCordobaCristo ReyDiego EchavarriaDoce De OctubreEduardo SantosEl ChagualoEl CucarachoEl DanubioEl DiamanteEl NogalEl PesebreEl PinalEl PobladoEl ProgresoEl RinconEl RodeoEl SaladoEl SalvadorEl SocorroEl VoladorEncisoEstacion VillaEstadioFatimaFerriniFlorenciaFlorida NuevaFrancisco Antonio ZeaGeronaGirardotGranadaGratamiraGuayabalGuayaquilHector Abad GomezJardin BotanicoJesus NazarenoJuan Del CorralKennedyLa AguacatalaLa AlmeriaLa AlpujarraLa AmericaLa CastellanaLa ColinaLa CruzLa FlorestaLa FranciaLa IguanaLa IndependenciaLa MilagrosaLa MotaLa PalmaLa PilaricaLa PraderaLaderaLas AcaciasLas AmericasLas BrisasLas IndependenciasLas MercedesLas PalmasLas PlayasLas VioletasLaurelesLoma De Los BernalLopez De MesaLorenaLoretoLos AlmendrosLos AngelesLos ColoresLos OlivosLos PinosLoyolaMalibuManilaManrique CentralManrique Central 2MiramarMirandaMiravalleMoraviaNaranjalNiquitao CentroNoelNueva Villa De AburraNuevos ConquistadoresOlaya HerreraOleoductoPablo EscobarPajaritoPalacio De ExposicionesPalenquePalermoPalermoPatio BonitoPedregalPerpetuo SocorroPlaya RicaPlayon De Los ComunerosPlaza ColonPobladoPoblado AlejandriaPradoRobledoRosalesSan Antonio De PradoSan BenitoSan DiegoSan GermanSan IsidroSan JavierSan JoaquinSan Miguel***San MitchelSan PabloSanta CruzSanta FeSanta GemaSanta Ines ManriqueSanta LuciaSanta Maria De Los AngelesSanta MonicaSanta TeresitaSantanderSevillaShellmarSimesaSimon BolivarSta Rosa De LimaSucreSuramericanaTejeloTencheToscanaTricentenarioTrinidadVeinte De JulioVelodromoVilla CarlotaVilla Del SocorroVilla FloraVilla HermosaVilla LiliamVilla PaulaVillatinaOtro
                  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NeighborhoodId&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NeighborhoodId']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='conten2']/div/app-main-request-service/app-add-address/div/div/div/div/div/div/div/form/div[4]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*) Barrio'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*) Ciudad'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El barrio es obligatorio'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*) Dirección'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
   </webElementXpaths>
</WebElementEntity>
