<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Servicios programados</name>
   <tag></tag>
   <elementGuidId>41a93514-aaf0-4fa4-ba8e-4a5212312de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='conten1']/nav/div/div/ms-sidenav/ul/ms-sidenav-item[5]/li[2]/ul/ms-sidenav-item[2]/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>closeMenuFromItems</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Servicios programados</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;conten1&quot;)/nav[@class=&quot;navbar navbar-default sidebar&quot;]/div[1]/div[1]/ms-sidenav[1]/ul[@class=&quot;nav navbar-nav&quot;]/ms-sidenav-item[@class=&quot;sidenav-item&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu forAnimate color-menu dropdown-items-menu menuwrap-open-items&quot;]/ms-sidenav-item[@class=&quot;sidenav-item&quot;]/li[1]/a[@class=&quot;closeMenuFromItems&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='conten1']/nav/div/div/ms-sidenav/ul/ms-sidenav-item[5]/li[2]/ul/ms-sidenav-item[2]/li/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ms-sidenav-item[5]/li[2]/ul/ms-sidenav-item[2]/li/a</value>
   </webElementXpaths>
</WebElementEntity>
